name: PHP Linter

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    php_linter:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        php_version: 7.3
                    -
                        php_version: 8.0

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.actions.php_version }}
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: vendor/bin/parallel-lint src tests
