name: Tests

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest
        name: PHP 8.0 tests

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none # disable xdebug, pcov

            -   uses: "ramsey/composer-install@v1"
            -   run: vendor/bin/phpunit
