name: Tests

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: vendor/bin/phpunit
