name: Tests

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.4', '8.0']
                include:
                    - php: '7.3'
                      dependencies: 'lowest'

        name: PHP ${{ matrix.php }} tests
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov

            -   run: composer update --prefer-lowest --no-progress --ansi
                if: "matrix.dependencies == 'lowest'"

            -   run: composer install --no-progress --ansi
                if: "matrix.dependencies != 'lowest'"

            -   run: vendor/bin/phpunit
